ARG BASE_CONTAINER=public-data-source
FROM $BASE_CONTAINER

COPY requirements-conda-dev.txt /tmp/
RUN conda install --yes \
    --file /tmp/requirements-conda-dev.txt && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

# Jupyter lab extension installs
RUN jupyter labextension install @jupyterlab/toc

USER root

# VS code-server install
RUN cd /opt \
  && wget --quiet --output-document=code-server.tar.gz \
     https://github.com/cdr/code-server/releases/download/v3.4.1/code-server-3.4.1-linux-amd64.tar.gz \
  && mkdir code-server \
  && tar --extract --file=code-server.tar.gz --directory=code-server --strip-components=1  \
  && rm code-server.tar.gz \
  && chmod a+x code-server/bin/code-server \
  && ln --symbolic /opt/code-server/bin/code-server /usr/local/bin/code-server \
  && code-server --install-extension ms-python.python \
  && code-server --install-extension njpwerner.autodocstring \
  && code-server --install-extension bungcip.better-toml
COPY docker/dev.code-workspace $WORK_DIR/
RUN mkdir $WORK_DIR/logs

# Override cmd on entry at:
# https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L130
# ENTRYPOINT ["tini", "-g", "--"]
# CMD ["start-notebook.sh"]
COPY docker/start-all.sh docker/start-vscode.sh /usr/local/bin/
RUN chmod a+rx /usr/local/bin/start-all.sh /usr/local/bin/start-vscode.sh

# This is critical because code-server will write to
# /home/jovyan/.local/share/code-server as root, and
# alter permissions on /home/jovyan/.local/share/jupyter
RUN fix-permissions "/home/${NB_USER}"

# Add dotenv module cli
COPY docker/fire-dotenv.sh /usr/local/bin/fire-dotenv
RUN chmod a+rx /usr/local/bin/fire-dotenv

USER $NB_UID

ENV PYLINTRC="$WORK_DIR/repos/public-data-source/.pylintrc"

CMD ["start-all.sh"]
